//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDepot.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarDepot.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are about to delete the selected task.
        /// </summary>
        internal static string CONTROL_MANAGEVEHICLETASKS_CONFIRMDELETE
        {
            get
            {
                return ResourceManager.GetString("CONTROL_MANAGEVEHICLETASKS_CONFIRMDELETE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string CONTROL_MANAGEVEHICLETASKS_CONFIRMDELETETITLE
        {
            get
            {
                return ResourceManager.GetString("CONTROL_MANAGEVEHICLETASKS_CONFIRMDELETETITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to *.xml.
        /// </summary>
        internal static string FILTER_ALL_XML
        {
            get
            {
                return ResourceManager.GetString("FILTER_ALL_XML", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vehicle&apos;s on lot.
        /// </summary>
        internal static string PAGES_ACTIVEVEHICLE_TAB_TITLE
        {
            get
            {
                return ResourceManager.GetString("PAGES_ACTIVEVEHICLE_TAB_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Vehicle&apos;s currently on the lot.
        /// </summary>
        internal static string PAGES_ACTIVEVEHICLE_TITLE
        {
            get
            {
                return ResourceManager.GetString("PAGES_ACTIVEVEHICLE_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading Vehicle&apos;s on lot.
        /// </summary>
        internal static string PAGES_ACTIVEVEHICLE_TITLE_LOADING
        {
            get
            {
                return ResourceManager.GetString("PAGES_ACTIVEVEHICLE_TITLE_LOADING", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string PAGES_VEHICLEINFOPAGE_ERROR
        {
            get
            {
                return ResourceManager.GetString("PAGES_VEHICLEINFOPAGE_ERROR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We were unable to save the vehicle updates.  It appears someone has made a change before you.  Please close and reopen this page to get the latest data..
        /// </summary>
        internal static string PAGES_VEHICLEINFOPAGE_ONCLOSING_UNABLETOSAVE
        {
            get
            {
                return ResourceManager.GetString("PAGES_VEHICLEINFOPAGE_ONCLOSING_UNABLETOSAVE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are about to close this page, please ensure you have saved all data before leaving.  Would you like to save now?.
        /// </summary>
        internal static string PAGES_VEHICLEINFOPAGE_ONCLOSING_WARNING
        {
            get
            {
                return ResourceManager.GetString("PAGES_VEHICLEINFOPAGE_ONCLOSING_WARNING", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        internal static string PAGES_VEHICLEINFOPAGE_ONCLOSING_WARNING_TITLE
        {
            get
            {
                return ResourceManager.GetString("PAGES_VEHICLEINFOPAGE_ONCLOSING_WARNING_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to General Vehicle Information.
        /// </summary>
        internal static string PAGES_VEHICLEINFOWINDOW_BASICINFO_TAB_TITLE
        {
            get
            {
                return ResourceManager.GetString("PAGES_VEHICLEINFOWINDOW_BASICINFO_TAB_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SystemAdminAccount.
        /// </summary>
        internal static string SYSTEMADMINACCOUNTNAME
        {
            get
            {
                return ResourceManager.GetString("SYSTEMADMINACCOUNTNAME", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VEHICLEADMINOBJECT_CREATENEWVEHICLE_ERROR.
        /// </summary>
        internal static string VEHICLEADMINOBJECT_CREATENEWVEHICLE_ERROR
        {
            get
            {
                return ResourceManager.GetString("VEHICLEADMINOBJECT_CREATENEWVEHICLE_ERROR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ERROR.
        /// </summary>
        internal static string ERROR
        {
            get
            {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CONTROL_ACTIONSCONTROL_TAB_TITLE.
        /// </summary>
        internal static string CONTROL_ACTIONSCONTROL_TAB_TITLE
        {
            get
            {
                return ResourceManager.GetString("CONTROL_ACTIONSCONTROL_TAB_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PAGE_VEHICLESEARCHPAGE_TITLE.
        /// </summary>
        internal static string PAGE_VEHICLESEARCHPAGE_TITLE
        {
            get
            {
                return ResourceManager.GetString("PAGE_VEHICLESEARCHPAGE_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PAGE_VEHICLETASKSEARCHPAGE_TITLE.
        /// </summary>
        internal static string PAGE_VEHICLETASKSEARCHPAGE_TITLE
        {
            get
            {
                return ResourceManager.GetString("PAGE_VEHICLETASKSEARCHPAGE_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PAGE_VEHICLESEARCHPAGE_TITLE.
        /// </summary>
        internal static string PAGES_VEHICLEINFOPAGE_CONFIRMDELETE
        {
            get
            {
                return ResourceManager.GetString("PAGES_VEHICLEINFOPAGE_CONFIRMDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAGE_VEHICLESEARCHPAGE_TITLE.
        /// </summary>
        internal static string PAGES_VEHICLEINFOPAGE_UNABLETODELETE
        {
            get
            {
                return ResourceManager.GetString("PAGES_VEHICLEINFOPAGE_UNABLETODELETE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PAGE_VEHICLESEARCHPAGE_TITLE.
        /// </summary>
        internal static string CUSTOMERINFOPAGE_ADDFILERESOURCE_REPLACEFILE
        {
            get
            {
                return ResourceManager.GetString("CUSTOMERINFOPAGE_ADDFILERESOURCE_REPLACEFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAGE_VEHICLESEARCHPAGE_TITLE.
        /// </summary>
        internal static string CUSTOMERINFOPAGE_ADDFILERESOURCE_REPLACEFILE_TITLE
        {
            get
            {
                return ResourceManager.GetString("CUSTOMERINFOPAGE_ADDFILERESOURCE_REPLACEFILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEHICLEINFOPAGE_IMPORTURL_PROMPT.
        /// </summary>
        internal static string VEHICLEINFOPAGE_IMPORTURL_PROMPT
        {
            get
            {
                return ResourceManager.GetString("VEHICLEINFOPAGE_IMPORTURL_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEHICLEINFOPAGE_IMPORTURL_TITLE.
        /// </summary>
        internal static string VEHICLEINFOPAGE_IMPORTURL_TITLE
        {
            get
            {
                return ResourceManager.GetString("VEHICLEINFOPAGE_IMPORTURL_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VEHICLEINFOPAGE_IMPORTURL_DATA.
        /// </summary>
        internal static string VEHICLEINFOPAGE_IMPORTURL_DATA
        {
            get
            {
                return ResourceManager.GetString("VEHICLEINFOPAGE_IMPORTURL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VEHICLEINFOPAGE_INVALID_URL.
        /// </summary>
        internal static string VEHICLEINFOPAGE_INVALID_URL
        {
            get
            {
                return ResourceManager.GetString("VEHICLEINFOPAGE_INVALID_URL", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PAGES_VEHICLEINFOPAGE_MISSINGINFO_CONFIRMDELETE.
        /// </summary>
        internal static string PAGES_VEHICLEINFOPAGE_MISSINGINFO_CONFIRMDELETE
        {
            get
            {
                return ResourceManager.GetString("PAGES_VEHICLEINFOPAGE_MISSINGINFO_CONFIRMDELETE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PAGE_CUSTOMERSEARCHPAGE_TITLE.
        /// </summary>
        internal static string PAGE_CUSTOMERSEARCHPAGE_TITLE
        {
            get
            {
                return ResourceManager.GetString("PAGE_CUSTOMERSEARCHPAGE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFORMATION.
        /// </summary>
        internal static string INFORMATION
        {
            get
            {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VEHICLEINFOPAGE_PRINT_BIWEEKLYRATE.
        /// </summary>
        internal static string VEHICLEINFOPAGE_PRINT_BIWEEKLYRATE
        {
            get
            {
                return ResourceManager.GetString("VEHICLEINFOPAGE_PRINT_BIWEEKLYRATE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PAGES_CUSTOMERINFOPAGE_CONFIRMDELETE.
        /// </summary>
        internal static string PAGES_CUSTOMERINFOPAGE_CONFIRMDELETE
        {
            get
            {
                return ResourceManager.GetString("PAGES_CUSTOMERINFOPAGE_CONFIRMDELETE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PAGES_CUSTOMERINFOPAGE_UNABLETODELETE.
        /// </summary>
        internal static string PAGES_CUSTOMERINFOPAGE_UNABLETODELETE
        {
            get
            {
                return ResourceManager.GetString("PAGES_CUSTOMERINFOPAGE_UNABLETODELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAGES_CUSTOMERINFOPAGE_MISSINGINFO_CONFIRMDELETE.
        /// </summary>
        internal static string PAGES_CUSTOMERINFOPAGE_MISSINGINFO_CONFIRMDELETE
        {
            get
            {
                return ResourceManager.GetString("PAGES_CUSTOMERINFOPAGE_MISSINGINFO_CONFIRMDELETE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PAGES_CUSTOMERINFOPAGE_ONCLOSING_UNABLETOSAVE.
        /// </summary>
        internal static string PAGES_CUSTOMERINFOPAGE_ONCLOSING_UNABLETOSAVE
        {
            get
            {
                return ResourceManager.GetString("PAGES_CUSTOMERINFOPAGE_ONCLOSING_UNABLETOSAVE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PAGES_VEHICLEINFOPAGE_ONCLOSING_CONFIRMNOSAVE.
        /// </summary>
        internal static string PAGES_VEHICLEINFOPAGE_ONCLOSING_CONFIRMNOSAVE
        {
            get
            {
                return ResourceManager.GetString("PAGES_VEHICLEINFOPAGE_ONCLOSING_CONFIRMNOSAVE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PAGES_CUSTOMERINFOPAGE_ONCLOSING_CONFIRMNOSAVE.
        /// </summary>
        internal static string PAGES_CUSTOMERINFOPAGE_ONCLOSING_CONFIRMNOSAVE
        {
            get
            {
                return ResourceManager.GetString("PAGES_CUSTOMERINFOPAGE_ONCLOSING_CONFIRMNOSAVE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to WARNING.
        /// </summary>
        internal static string WARNING
        {
            get
            {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CONTROL_IMAGETHUMBNAILCONROL_CONFIRMDELETE.
        /// </summary>
        internal static string CONTROL_IMAGETHUMBNAILCONROL_CONFIRMDELETE
        {
            get
            {
                return ResourceManager.GetString("CONTROL_IMAGETHUMBNAILCONROL_CONFIRMDELETE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PAYOUTLIENTASK.
        /// </summary>
        internal static string PAYOUTLIENTASK
        {
            get
            {
                return ResourceManager.GetString("PAYOUTLIENTASK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to VERIFYFINANCEDEPOSIT.
        /// </summary>
        internal static string VERIFYFINANCEDEPOSIT
        {
            get
            {
                return ResourceManager.GetString("VERIFYFINANCEDEPOSIT", resourceCulture);
            }
        }
 
        /// <summary>
        ///   Looks up a localized string similar to CONTROL_MANAGEVEHICLETASKS_CANNOTCOMPLETETASK.
        /// </summary>
        internal static string CONTROL_MANAGEVEHICLETASKS_CANNOTCOMPLETETASK
        {
            get
            {
                return ResourceManager.GetString("CONTROL_MANAGEVEHICLETASKS_CANNOTCOMPLETETASK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CONTROL_TASKSCONTROL_TAB_TITLE.
        /// </summary>
        internal static string CONTROL_TASKSCONTROL_TAB_TITLE
        {
            get
            {
                return ResourceManager.GetString("CONTROL_TASKSCONTROL_TAB_TITLE", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SOLDCARCLEANINGTASK.
        /// </summary>
        internal static string SOLDCARCLEANINGTASK
        {
            get
            {
                return ResourceManager.GetString("SOLDCARCLEANINGTASK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NEWCAROILCHANGETASK.
        /// </summary>
        internal static string NEWCAROILCHANGETASK
        {
            get
            {
                return ResourceManager.GetString("NEWCAROILCHANGETASK", resourceCulture);
            }
        }
        
       
    }
}
